# Tools & Packages {#tools_packages}

## Libraries

- [Fast.ai](https://docs.fast.ai)
    - [Github page](https://github.com/fastai/fastai)
    - Simplifies training fast and accurate neural nets using modern best practices, abstracting away all of the nitty gritty work that can come with implementing deep neural networks in practice.
    
- [Detectron](https://ai.facebook.com/tools/detectron/)
    - [Github page](https://github.com/facebookresearch/Detectron)
    - Detectron is Facebook AI’s research platform for object detection and instance segmentation research, written in Caffe2.
    
- [FastText](https://research.fb.com/blog/2016/08/fasttext/)
    - [Github page](https://github.com/facebookresearch/fastText)
    - Designed for efficient learning of word representations and sentence classification.

## Open-Source

- [OpenML](https://www.openml.org)
    - [Github page](https://github.com/openml/OpenML)
    - An open-source collection of datasets and algorithms with APIs for various languages to integrate OpenML into your own tools.

## Dataset Creation with Weak Supervision

- [Snorkel: A System for Fast Training Data Creation](https://hazyresearch.github.io/snorkel/)
    - "A system for rapidly creating training sets with weak supervision."

## Cloud Computing

- [AWS ParallelCluster](https://aws.amazon.com/blogs/opensource/aws-parallelcluster/)
    - "An AWS supported, open source cluster management tool that makes it easy for scientists, researchers, and IT administrators to deploy and manage High Performance Computing (HPC) clusters in the AWS cloud."